### ISSUE TITLE
Error: 304

### ISSUE THREAD

**Issue by stereobooster** [peterbe/minimalcss#162]
Error trace for `minimalcss@0.6.3`

```
🔥  / Error: 304 on http://localhost:45678/
 at Promise (/node_modules/minimalcss/src/run.js:249:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:78612) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Network.getResponseBody): Target closed.
(node:78612) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:78612) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Protocol error (Network.getResponseBody): Target closed.
error An unexpected error occurred: "Command failed.
```

Update `minimalcss` to `0.7.3` error happens at  `node_modules/minimalcss/src/run.js:245:29`

`304` stands for `Not Modified` so maybe we do not need to throw error here?

**Comment by stereobooster** [comment]
Update `minimalcss` to `0.7.3` error happens at  `node_modules/minimalcss/src/run.js:245:29`

**Comment by stereobooster** [comment]
Shouldn't it be `if (withoutjavascript)`?

```js
      if (!withoutjavascript) {
        // First, go to the page with JavaScript disabled.
        await page.setJavaScriptEnabled(false);
        response = await page.goto(pageUrl);
        if (!response.ok()) {
          return safeReject(new Error(`${response.status()} on ${pageUrl}`));
        }
        const htmlVanilla = await page.content();
        doms.push(cheerio.load(htmlVanilla));
        await page.setJavaScriptEnabled(true);
      }
```

**Comment by stereobooster** [comment]
Another finding: [Google web fonts uses User Agent Sniffing](https://stackoverflow.com/questions/19467122/how-does-google-web-fonts-decide-which-version-of-a-font-to-provide-to-my-browse), so Google fonts css should be left untouched.

**Comment by peterbe** [comment]
The whole point of us looking at statuses where the code was [300, 400] is so that we can write down what the URL redirects to. That way we can "track" what Chrome does already but have a record of all redirects. 
So ultimately we're only really interested in "Was there a redirect?". We currently have this:

```javascript
        } else if (response.status() >= 300) {
          // If the 'Location' header points to a relative URL,
          // convert it to an absolute URL.
          // If it already was an absolute URL, it stays like that.
          const redirectsTo = new url.URL(
            response.headers().location,
            responseUrl
          ).toString();
          redirectResponses[responseUrl] = redirectsTo;
```

Can we change that to:
```diff
        } else if (response.status() >= 300) {
+         // Not all 3xx statuses means a redirect happened.
+         if (response.headers().location) {
+           // There was a redirect!
            // If the 'Location' header points to a relative URL,
            // convert it to an absolute URL.
            // If it already was an absolute URL, it stays like that.
            const redirectsTo = new url.URL(
              response.headers().location,
              responseUrl
            ).toString();
            redirectResponses[responseUrl] = redirectsTo; 
+         }
```

That way, if it was a 304 it stays within this block (and doesn't attempt to do `response.text().then(text => {`).

**Comment by peterbe** [comment]
https://github.com/peterbe/minimalcss/pull/165 is merged now.
