### ISSUE TITLE
cannot read property 'ok' of null

### ISSUE THREAD

**Issue by bdefore** [peterbe/minimalcss#269]
Not sure if this is related to react-snap or minimalcss, but it throws here, so I'll file. react-snap 0.19.1 which is using 0.7.10 of minimalcss

When I pass it a url that should be valid, I get the following output:

```
💬  console.log at /ja/product/redvalentino-wool-vneck-sweater-with-bow-detail/nm_sku179600022: Link [object Object] was not given a destination, bypassing render
💬  console.log at /ja/product/redvalentino-wool-vneck-sweater-with-bow-detail/nm_sku179600022: Initiating new session... JSHandle@object
💬  console.log at /ja/product/redvalentino-wool-vneck-sweater-with-bow-detail/nm_sku179600022: Link [object Object] was not given a destination, bypassing render
🔥  error at /ja/product/redvalentino-wool-vneck-sweater-with-bow-detail/nm_sku179600022 TypeError: Cannot read property 'ok' of null
    at isOk (/home/me/code/localised/lithos/node_modules/minimalcss/src/run.js:13:35)
    at Promise (/home/me/code/localised/lithos/node_modules/minimalcss/src/run.js:275:14)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
/home/me/code/localised/lithos/node_modules/highland/lib/index.js:1492
            throw new Error('Cannot write to stream after nil');
```

**Comment by peterbe** [comment]
What version of minimalcss do you have in your node_modules?

You can test by running `./node_modules/.bin/minimalcss --version`

**Comment by bdefore** [comment]
```→ npm ls minimalcss
lithos@1.8.0 /home/bdefore/code/localised/lithos
└─┬ react-snap@1.19.0
  └── minimalcss@0.7.10 

→ ./node_modules/.bin/minimalcss --version
0.7.10```

**Comment by cj** [comment]
@peterbe @bdefore I have this error too, it happens when you're using the create-react-app service worker and reactSnap option `inlineCss: true`.

**Comment by cj** [comment]
If anyone else runs into this, just change your `src/index` to the following:

```javascript
const rootElement = document.getElementById('root')

if (rootElement!.hasChildNodes()) {
  ReactDOM.hydrate(<App />, rootElement)

  // If you want your app to work offline and load faster, you can change
  // unregister() to register() below. Note this comes with some pitfalls.
  // Learn more about service workers: http://bit.ly/CRA-PWA
  serviceWorker.register()
} else {
  ReactDOM.render(<App />, rootElement)
}
```

**Comment by stereobooster** [comment]
If the issue with `serviceWorker` in `react-snap` there is this ticket for it https://github.com/stereobooster/react-snap/issues/314

**Comment by stereobooster** [comment]
This is not an error of minimalcss. This is an issue in react-snap (there is no try-catch around minimalcss https://github.com/stereobooster/react-snap/pull/263/files#diff-168726dbe96b3ce427e7fedce31bb0bcR261). Nothing to fix in minimalcss.
