### ISSUE TITLE
`Error: 307 on http://www.youtube.com/embed/VcjzHMhBtf0?rel=0`

### ISSUE THREAD

**Issue by peterbe** [peterbe/minimalcss#82]
Steps to reproduce:
```
▶ ./bin/minimalcss.js -d -o /tmp/bootstrap.before.css http://blog.getbootstrap.com/
Error: 307 on http://www.youtube.com/embed/VcjzHMhBtf0?rel=0
    at Page.page.on.response (/Users/peterbe/dev/JAVASCRIPT/minimalcss/src/run.js:129:29)
    at emitOne (events.js:115:13)
    at Page.emit (events.js:210:7)
    at NetworkManager.Page._networkManager.on.event (/Users/peterbe/dev/JAVASCRIPT/minimalcss/node_modules/puppeteer/lib/Page.js:94:75)
    at emitOne (events.js:115:13)
    at NetworkManager.emit (events.js:210:7)
    at NetworkManager._handleRequestRedirect (/Users/peterbe/dev/JAVASCRIPT/minimalcss/node_modules/puppeteer/lib/NetworkManager.js:182:10)
    at NetworkManager._onRequestIntercepted (/Users/peterbe/dev/JAVASCRIPT/minimalcss/node_modules/puppeteer/lib/NetworkManager.js:155:14)
    at emitOne (events.js:115:13)
    at CDPSession.emit (events.js:210:7)
```

**Comment by stereobooster** [comment]
Puppeteer for some reason considers only 2xx responses as successful.

```js
ok() {
  return this._status >= 200 && this._status <= 299;
}
```

https://httpstatuses.com/307 is redirect.

We can do

```js
if (response.status() >= 400) {
  return safeReject(new Error(`Response status ${response.status()} on ${pageUrl}`))
}
```
